version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=kohaku
      - POSTGRES_PASSWORD=kmanjing
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
